# Generated by Django 5.1.4 on 2025-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('grocery', 'Grocery'), ('rent', 'Rent'), ('bills', 'Bills'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('category', 'month')},
            },
        ),
    ]
