# Generated by Django 3.0.5 on 2025-01-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_monthlybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('savings', 'Savings')], max_length=50)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('month', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('savings', 'Savings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('savings', 'Savings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
